Install NVM v11

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,11 +15,13 @@ jobs:
       - name: Install NVM (macOS)
         run: |
           brew install nvm
+          mkdir -p ~/.nvm
+          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
 
       - name: Load NVM
         run: |
           export NVM_DIR="$HOME/.nvm"
-          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" || echo "nvm.sh not found"
           echo "NVM_DIR=$NVM_DIR" >> $GITHUB_ENV
 
       - name: Verify NVM Installation
